export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN',
  PRINCIPAL: 'PRINCIPAL',
  TEACHER: 'TEACHER',
  ACCOUNTANT: 'ACCOUNTANT',
  RECEPTIONIST: 'RECEPTIONIST',
  DRIVER: 'DRIVER',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT',
  STAFF: 'STAFF',
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];

export const PERMISSIONS = {
  // Students
  STUDENTS_VIEW: 'students.view',
  STUDENTS_CREATE: 'students.create',
  STUDENTS_UPDATE: 'students.update',
  STUDENTS_DELETE: 'students.delete',

  // Attendance
  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_MARK: 'attendance.mark',
  ATTENDANCE_UPDATE: 'attendance.update',

  // Fees
  FEES_VIEW: 'fees.view',
  FEES_CREATE: 'fees.create',
  FEES_COLLECT: 'fees.collect',
  FEES_REFUND: 'fees.refund',

  // Transport
  TRANSPORT_VIEW: 'transport.view',
  TRANSPORT_MANAGE: 'transport.manage',
  TRANSPORT_TRACK: 'transport.track',

  // Academics
  ACADEMICS_MANAGE: 'academics.manage',
  ACADEMICS_VIEW: 'academics.view',

  // Exams
  EXAMS_MANAGE: 'exams.manage',
  EXAMS_MARKS_ENTER: 'exams.marks.enter',
  EXAMS_VIEW: 'exams.view',

  // Schools (Super Admin)
  SCHOOLS_MANAGE: 'schools.manage',
  SCHOOLS_VIEW: 'schools.view',
  SCHOOLS_CREATE: 'schools.create',
  SCHOOLS_UPDATE: 'schools.update',
  SCHOOLS_ACTIVATE: 'schools.activate',
  SCHOOLS_SUSPEND: 'schools.suspend',
  SCHOOLS_ARCHIVE: 'schools.archive',

  // Users
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_ACTIVATE: 'users.activate',
  USERS_DEACTIVATE: 'users.deactivate',

  // Staff
  STAFF_VIEW: 'staff.view',
  STAFF_CREATE: 'staff.create',
  STAFF_UPDATE: 'staff.update',
  STAFF_DELETE: 'staff.delete',

  // Teachers
  TEACHERS_VIEW: 'teachers.view',
  TEACHERS_CREATE: 'teachers.create',
  TEACHERS_UPDATE: 'teachers.update',
  TEACHERS_DELETE: 'teachers.delete',

  // Parents
  PARENTS_VIEW: 'parents.view',
  PARENTS_CREATE: 'parents.create',
  PARENTS_UPDATE: 'parents.update',
  PARENTS_DELETE: 'parents.delete',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Role to permissions mapping
export const DEFAULT_ROLE_PERMISSIONS: Record<Role, string[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  SCHOOL_ADMIN: [
    PERMISSIONS.SCHOOLS_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_ACTIVATE,
    PERMISSIONS.USERS_DEACTIVATE,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.STAFF_DELETE,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.TEACHERS_CREATE,
    PERMISSIONS.TEACHERS_UPDATE,
    PERMISSIONS.TEACHERS_DELETE,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_UPDATE,
    PERMISSIONS.STUDENTS_DELETE,
    PERMISSIONS.PARENTS_VIEW,
    PERMISSIONS.PARENTS_CREATE,
    PERMISSIONS.PARENTS_UPDATE,
    PERMISSIONS.PARENTS_DELETE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_CREATE,
    PERMISSIONS.FEES_COLLECT,
    PERMISSIONS.FEES_REFUND,
    PERMISSIONS.TRANSPORT_VIEW,
    PERMISSIONS.TRANSPORT_MANAGE,
    PERMISSIONS.TRANSPORT_TRACK,
    PERMISSIONS.ACADEMICS_MANAGE,
    PERMISSIONS.ACADEMICS_VIEW,
    PERMISSIONS.EXAMS_MANAGE,
    PERMISSIONS.EXAMS_MARKS_ENTER,
    PERMISSIONS.EXAMS_VIEW,
  ],
  PRINCIPAL: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.TRANSPORT_VIEW,
    PERMISSIONS.ACADEMICS_MANAGE,
    PERMISSIONS.ACADEMICS_VIEW,
    PERMISSIONS.EXAMS_VIEW,
  ],
  TEACHER: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ACADEMICS_VIEW,
    PERMISSIONS.EXAMS_MARKS_ENTER,
    PERMISSIONS.EXAMS_VIEW,
  ],
  ACCOUNTANT: [
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_CREATE,
    PERMISSIONS.FEES_COLLECT,
    PERMISSIONS.FEES_REFUND,
  ],
  RECEPTIONIST: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
  ],
  DRIVER: [
    PERMISSIONS.TRANSPORT_TRACK,
  ],
  PARENT: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.TRANSPORT_TRACK,
    PERMISSIONS.EXAMS_VIEW,
  ],
  STUDENT: [
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.EXAMS_VIEW,
  ],
  STAFF: [
    PERMISSIONS.ATTENDANCE_VIEW,
  ],
};
